from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "reversible_topology_recovery_lstm_v10"
CHECKPOINT_DIR = OUTPUT_DIR / "checkpoints"
VISUAL_CHECKPOINT = CHECKPOINT_DIR / "visual_retrieval_A_only.pt"
TEMPORAL_CHECKPOINT = CHECKPOINT_DIR / "reversible_topology_recovery_lstm_A_only.pt"

ROUTE_ROOTS = [
    Path("/yh/study/new_data_2/model_dataset_new_1_flight"),
    Path("/yh/study/new_data_2/model_dataset_new_2_flight"),
    Path("/yh/study/new_data/model_dataset_flight"),
]
ROUTE_NAMES = ["route_A", "route_B", "route_C"]
WAYPOINT_DIR = PROJECT_ROOT / "route_waypoints"
WAYPOINT_FILES = {
    "route_A": WAYPOINT_DIR / "route_A_waypoints.json",
    "route_B": WAYPOINT_DIR / "route_B_waypoints.json",
    "route_C": WAYPOINT_DIR / "route_C_waypoints.json",
}
SAT_IMAGE = Path("/yh/study/sim_data/sim_competition_crop_check/sim_map_competition_roi_crop.png")
SAT_JSON = Path("/yh/study/sim_data/sim_competition_crop_check/sim_map_competition_roi_crop_worldfile_epsg3826.json")

BACKBONE_NAME = "hf-hub:timm/MobileCLIP2-S2-OpenCLIP"
CLIP_DIM = 512
EMBED_DIM = 512
IMAGE_SIZE = 256
UAV_CENTER_CROP_SIZE = 256
UAV_CENTER_MAX_SQUARE_CROP = False
UAV_RESIZE_AFTER_CROP = None
TRAIN_UAV_AUGMENT = False
SAT_CROP_SIZE = 320
SAT_STRIDE = 32
USE_COORD_ENCODER = False
USE_QAH_MS_RELATION = False
USE_BASIN_RANK_MS = False
MOTION_SPATIAL_SIZE = 4
VISUAL_EPOCHS = 30
VISUAL_LR = 3e-4
VISUAL_WEIGHT_DECAY = 1e-3
VISUAL_BATCH_SIZE = 64
VISUAL_CACHE_BATCH_SIZE = 256
VISUAL_EARLY_STOPPING_PATIENCE = 8
VISUAL_LABEL_SMOOTHING = 0.05
VISUAL_COORD_LOSS_WEIGHT = 0.25
MEANSHIFT_SCORE_TAU = 0.30
MEANSHIFT_BANDWIDTH_M = 8.0
MEANSHIFT_ITERATIONS = 3
GRID_SIZE = 6
LOCAL_PRIOR_JITTER_M = 12.0
CANDIDATE_CAPTURE_RADIUS_M = 7.5
MIN_TRAIN_CAPTURE_RATE = 0.95
TRAIN_FRACTION = 0.70
VAL_FRACTION = 0.15
TEST_FRACTION = 0.15
SPLIT_GUARD_FRAMES = 16

# v10 normal tracking: only forward half of conceptual 6x6.
FORWARD_CANDIDATE_COUNT = 18
FORWARD_HALF_EPS_M = 0.0
ROUTE_CORRIDOR_HALF_WIDTH_M = 36.0
ROUTE_ALONG_BACK_PADDING_M = 8.0
ROUTE_ALONG_FORWARD_PADDING_M = 12.0

# True recovery: whole previous/current/next leg corridors, no Pred center, no forward mask.
RECOVERY_NEIGHBOR_LEG_RADIUS = 1
RECOVERY_TOPK = 24

LEG_PREVIOUS = 0
LEG_CURRENT = 1
LEG_NEXT = 2
LEG_STATE_COUNT = 3
LEG_EVIDENCE_TOPK = 12
LEG_EVIDENCE_DIM = 12
LEG_TRAIN_PERTURB_PROB = 0.10

HYPOTHESIS_HOLD = 0
HYPOTHESIS_LOCAL = 1
HYPOTHESIS_RECOVERY = 2
HYPOTHESIS_COUNT = 3
LSTM_HIDDEN_DIM = 256
LSTM_FEATURE_DIM = 128
LSTM_DROPOUT = 0.10
BRANCH_SOFTMAX_TEMPERATURE = 1.0
ROUTE_CONTEXT_DIM = 6

TEMPORAL_EPOCHS = 40
TEMPORAL_LR = 2e-4
TEMPORAL_WEIGHT_DECAY = 1e-3
TBPTT_STEPS = 32
GRAD_CLIP_NORM = 5.0
LOSS_POSITION = 1.00
LOSS_BRANCH = 0.40
LOSS_LEG_STATE = 0.55
LOSS_STEP = 0.10
LOSS_VARIANCE_NLL = 0.05

KALMAN_INIT_POSITION_VAR = 9.0
KALMAN_Q_POSITION = 0.35
KALMAN_R_MIN_VAR = 0.8
KALMAN_R_MAX_VAR = 49.0
JUMP_TOLERANCE_M = 3.0

VIDEO_FPS = 12.0
VIDEO_WIDTH = 1800
VIDEO_HEIGHT = 900
FRAME_LABEL_INTERVAL = 100
PROCESS_SNAPSHOT_COUNT = 12
SEED = 2029
DEVICE = "cuda"
FEATURE_CACHE_DTYPE = "float16"
