#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}"
STAMP="$(date +%Y%m%d_%H%M%S)"
SUITE="${FORMAL_SUITE_ROOT:-${ROOT}/v39_otherdata/formal_bearing_paper_${STAMP}}"
export FORMAL_SUITE_ROOT="${SUITE}"
export BEARING_DATASET_ROOT="${BEARING_DATASET_ROOT:-/yh/study/cvpr_data/Bearing_UAV_90K}"
export TEMPORAL_EPOCHS="${TEMPORAL_EPOCHS:-100}"
export VISUAL_EPOCHS="${VISUAL_EPOCHS:-30}"
export PATIENCE="${PATIENCE:-4}"
export SEED="${SEED:-2033}"
export CPU_THREADS_PER_CITY="${CPU_THREADS_PER_CITY:-2}"
export CACHE_BATCH_SIZE="${CACHE_BATCH_SIZE:-128}"
export CPU_NICE="${CPU_NICE:-5}"
export UPLOAD_RESULTS="${UPLOAD_RESULTS:-0}"
echo "============================================================"
echo "BEARING-UAV PAPER FULL SUITE"
echo "Suite   : ${SUITE}"
echo "Dataset : ${BEARING_DATASET_ROOT}"
echo "Cities  : A/B/C/D"
echo "Outputs : localization + heading + route diagnostics + tables"
echo "============================================================"
bash v39_otherdata/run_bearing_formal_v5_smooth.sh
bash v39_otherdata/run_bearing_paper_benchmark.sh "${SUITE}"
echo "[FULL PAPER SUITE DONE] ${SUITE}/paper_benchmark"
